<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
	<title>M10-Portfolio</title>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
	<link rel="stylesheet" href="../css/normalize.css">
	<link href="https://fonts.googleapis.com/css?family=Bree+Serif" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
	<link rel="stylesheet" href="../css/style.css">
</head>
<body>
	<header>
		<h1><img src="../img/logo.svg">John Doe</h1><!--
		--><nav>
		<div class = "nav"><i class="fas fa-home"></i><a href="index.php"></i>Accueil</a></div><!--
		--><div class = "nav"><i class="fas fa-search"></i><a href="">Chercher un article</a></div><!--
		--><div class = "nav"><i class="fas fa-user"></i><a href="users.php">S'inscrire</a></div><!--
			<?php if(isset($_SESSION['user'])) : ?>
		--><div class = "nav"><i class="fas fa-sign-in-alt"></i><a href="disconnect.php">Déconnexion</a></div><!--
		<?php else : ?>
		--><div class = "nav"><i class="fas fa-sign-in-alt"></i><a href="connect.php">Connexion</a></div><!--
		<?php endif ?>
	--><div class = "nav"><i class="fas fa-folder-open"></i><a href="../admin/src/form.php"></i>Administration</a></div>
</nav>
</header>

	<?php if(isset($_SESSION['user'])) : ?>
	<p> Bienvenue sur notre blog, vous êtes connecté sous l'identifiant <?= $_SESSION['user']['pseudo'] ?></p>
	<?php endif ?>

	<?php include $template ?>

<footer>
  <a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/"><img alt="Propriété de la 3W Academy" style="border-width:0" src="https://3wa.fr/wp-content/themes/3wa2015/img/logos/big.png" /></a><br />Cet exercice de <a href="https://3wa.fr">3W Academy</a> est mis à disposition <a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/">pour l'usage personnel des étudiants, Pas de Rediffusion - Attribution - Pas d'Utilisation Commerciale - Pas de Modification - International</a>.Les autorisations au-delà du champ de cette licence peuvent être obtenues auprès de <a href="mailto:contact@3wa.fr" rel="cc:morePermissions">contact@3wa.fr</a>. Les maquettes ont été réalisées par<a href="http://www.justine-muller.fr">Justine Muller</a>.
</footer>
</body>
</html>
