<main class ="container">
<section class="contact">
  <h2>-Postez votre article-</h2>
  <form class="" action="form.php" method="post">
    <input class = "mail" type="date" placeholder="date" name="datePublication" value = "datePublication">
    <input class = "mail" type="text" placeholder="votre titre" name="titre">
    <div class = "clear"></div>
    <input class = "message" type="textarea" placeholder="Votre article" name="texte">
    <p>
      <input class = "submit" type="submit" value="add" name="add">
    </p>
  </form>
</main>
