<main class ="container">
	<h2>-Derniers articles publiés-</h2>

	<h2><?= $oneArticle['titre'] ?></h2>
	<h3><strong> Date de publication : <?= substr($oneArticle['dateCreation'],0,10)?></strong><h3>
		<h3><strong> Auteur : <?= $oneArticle['prenom']." ".$oneArticle['nom']?></strong><h3>
			<img class ="picture" src=../img/<?= $oneArticle['image'] ?>>
			<p><?= $oneArticle['texte'] ?></p>

			<!--<p>?= $showComment[0]['texte'] ?></p>-->
			<?php if(isset($_SESSION['user'])) : ?>
			<h2>Ecrivez un commentaire</h2>
			<form class="" action="comment.php" method="post">
				<!-- input caché qui reprend l'id de l'article que nous voulons commenter et qui affecte
				cette valeur dans commentaire ("billet" qui est = à l'id dans billet) -->
				<input type="hidden" name="billet" value="<?= $oneArticle['id']?>" />
				<input type="hidden" name="auteur" value="<?= $_SESSION['user']['id']?>" />
				<textarea type="text" class= "post" name="texte" placeholder ="Ecrire votre commentaire" ></textarea>
				<p>
					<input class = "submit" type="submit" value="add" name="add">
				</p>
				<?php endif ?>

				<h2>Commentaires</h2>

					<?php if(!isset($_SESSION['user'])) : ?>
					<p> Vous devez avoir un compte sur notre blog pour commenter un article. Inscrivez vous <a href = "users.php"> ici </a> </p>
					<?php endif ?>

				<?php foreach($showComment as $a) : ?>
					<p> Nom : <?= $a['prenom'] ?></p>
					<p> Date : <?= substr($a['datePublication'],0,10) ?></p>
					<p> <?= $a['texte'] ?></p>
				<?php endforeach ?>
		</form>
	</main>
