<main class ="container">
<section class="contact">
  <h2>-Inscrivez-vous à ce super blog!!! -</h2>
  <form class="" action="users.php" method="post">

    <input class = "mail" type="text" placeholder="votre nom" name="nom">
    <input class = "mail" type="text" placeholder="votre prenom" name="prenom">
    <input class = "mail" type="text" placeholder="votre email" name="email">
    <input class = "mail" type="text" placeholder="choisir un pseudo" name="pseudo">
    <input class = "mail" type="text" placeholder="choisir un mot de passe" name="mot_de_passe">


    <p>
      <input class = "submit" type="submit" value="add" name="add">
    </p>
  </form>
</main>
